Repository cookies-mod/mod, pull requests merged in 2024-08, with the labels that each got.

#58 feat(Command): add a warp shortcut command
  src/main/java/dev/morazzer/cookies/mod/CookiesMod.java
  src/main/java/dev/morazzer/cookies/mod/commands/WarpCommand.java
  src/main/java/dev/morazzer/cookies/mod/repository/constants/RepositoryConstants.java
  src/main/java/dev/morazzer/cookies/mod/repository/constants/Warps.java
Labels: enhancement, in progress

#67 add a ping display to the actionbar
  src/main/java/dev/morazzer/cookies/mod/config/categories/MiscConfig.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/MiscFeatures.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/render/PingDisplay.java
  src/main/java/dev/morazzer/cookies/mod/render/types/BlockHighlight.java
  src/main/java/dev/morazzer/cookies/mod/utils/SkyblockUtils.java
  src/main/java/dev/morazzer/cookies/mod/utils/mixins/ClientPlayNetworkHandlerMixin.java
  src/main/java/dev/morazzer/cookies/mod/utils/mixins/PingMeasurerMixin.java
  src/main/resources/cookies-mod.utils.mixins.json
Labels: enhancement, in progress

#70 change handling of craft helper item
  src/main/java/dev/morazzer/cookies/mod/config/ConfigKeys.java
  src/main/java/dev/morazzer/cookies/mod/config/categories/HelpersConfig.java
  src/main/java/dev/morazzer/cookies/mod/events/InventoryEvents.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/ForgeRecipes.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/InventoryModifier.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/ModifyRecipeScreen.java
  src/main/java/dev/morazzer/cookies/mod/utils/items/types/MiscDataComponentTypes.java
  src/main/java/dev/morazzer/cookies/mod/utils/skyblock/SelectSlotInventory.java
Labels: enhancement

#72 feat: add github actions
  .github/dependabot.yml
  .github/workflows/build-on-push.yml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/cm/tasks/CreateBuildInfo.java
  buildSrc/src/main/java/cm/tasks/GitUtils.java
  buildSrc/src/main/java/cm/tasks/ModifyJarName.java
Labels: enhancement

#79 feat(ItemSearch): rework item search screen and add tabs
  src/main/java/dev/morazzer/cookies/mod/CookiesMod.java
  src/main/java/dev/morazzer/cookies/mod/commands/CookieCommand.java
  src/main/java/dev/morazzer/cookies/mod/config/screen/ConfigScreen.java
  src/main/java/dev/morazzer/cookies/mod/config/screen/InventoryConfigScreenConstants.java
  src/main/java/dev/morazzer/cookies/mod/config/screen/TabConstants.java
  src/main/java/dev/morazzer/cookies/mod/data/DataMigrations.java
  src/main/java/dev/morazzer/cookies/mod/data/Migration.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/ProfileStorage.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/Item.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/ItemCompound.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/ItemSource.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/ItemSources.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/sources/InventoryItemSource.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/sources/IslandChestItemSource.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/sources/SackItemSource.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/sources/StorageItemSource.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/migrations/ProfileDataMigration_0001.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/profile/GlobalProfileStorage.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/sub/StorageData.java
  src/main/java/dev/morazzer/cookies/mod/features/mining/PuzzlerSolver.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/items/StorageTracker.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/CraftHelper.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/StoragePreview.java
  src/main/java/dev/morazzer/cookies/mod/repository/RepositoryItem.java
  src/main/java/dev/morazzer/cookies/mod/screen/CookiesScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/ItemSearchScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/ScrollbarScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/search/ItemSearchCategories.java
  src/main/java/dev/morazzer/cookies/mod/screen/search/ItemSearchScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/search/ItemSourceCategories.java
  src/main/java/dev/morazzer/cookies/mod/services/ItemSearchService.java
  src/main/java/dev/morazzer/cookies/mod/utils/items/ItemTooltipComponent.java
  src/main/java/dev/morazzer/cookies/mod/utils/skyblock/inventories/ItemBuilder.java
Labels: enhancement

#81 feat(SackTracker): fix items not being tracked in some cases
  src/main/java/dev/morazzer/cookies/mod/features/misc/items/SackTrackerListener.java
Labels: bug

#86 fix(Repository): fix a crash caused by missing tier value
  src/main/java/dev/morazzer/cookies/mod/repository/RepositoryItem.java
Labels: bug, high priority

#91 feat(CraftHelper): make craft helper positionable
  gradle.properties
  src/datagen/java/dev/morazzer/cookies/mod/datagen/lang/EnglishLanguageProvider.java
  src/main/generated/.gitignore
  src/main/generated/assets/cookies-mod/lang/en_us.json
  src/main/java/dev/morazzer/cookies/mod/commands/dev/DebugSubCommand.java
  src/main/java/dev/morazzer/cookies/mod/commands/dev/debug/OpenCraftHelperPlacementScreen.java
  src/main/java/dev/morazzer/cookies/mod/commands/dev/debug/ProfileDataDebugCommand.java
  src/main/java/dev/morazzer/cookies/mod/commands/dev/debug/SetSelectedCraftHelperItemDebugCommand.java
  src/main/java/dev/morazzer/cookies/mod/config/categories/HelpersConfig.java
  src/main/java/dev/morazzer/cookies/mod/config/screen/ConfigScreen.java
  src/main/java/dev/morazzer/cookies/mod/config/system/editor/ButtonEditor.java
  src/main/java/dev/morazzer/cookies/mod/config/system/editor/ConfigOptionEditor.java
  src/main/java/dev/morazzer/cookies/mod/config/system/editor/TextDisplayEditor.java
  src/main/java/dev/morazzer/cookies/mod/config/system/options/ButtonOption.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/ProfileStorage.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/items/ItemSources.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/profile/IslandChestStorage.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/sub/SackTracker.java
  src/main/java/dev/morazzer/cookies/mod/data/profile/sub/StorageData.java
  src/main/java/dev/morazzer/cookies/mod/features/farming/garden/PlotPriceBreakdown.java
  src/main/java/dev/morazzer/cookies/mod/features/farming/garden/visitors/VisitorHelper.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/items/SackInventoryTracker.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/ModifyRecipeScreen.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/UtilsFeatures.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/CraftHelper.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/CraftHelperLocation.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/CraftHelperPlacement.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/CraftHelperTooltipPositioner.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/EvaluationContext.java
  src/main/java/dev/morazzer/cookies/mod/features/misc/utils/crafthelper/StackCountContext.java
  src/main/java/dev/morazzer/cookies/mod/screen/CookiesScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/inventory/ForgeRecipeScreen.java
  src/main/java/dev/morazzer/cookies/mod/screen/search/ItemSearchScreen.java
  src/main/java/dev/morazzer/cookies/mod/translations/TranslationKeys.java
  src/main/java/dev/morazzer/cookies/mod/utils/RenderUtils.java
  src/main/java/dev/morazzer/cookies/mod/utils/accessors/InventoryScreenAccessor.java
  src/main/java/dev/morazzer/cookies/mod/utils/mixins/HandledScreenMixin.java
  src/main/java/dev/morazzer/cookies/mod/utils/skyblock/components/PressableField.java
  src/main/java/dev/morazzer/cookies/mod/utils/skyblock/inventories/ClientSideInventory.java
  src/main/resources/assets/cookies-mod/textures/gui/blank.png
Labels: bug, enhancement
